USE aqi

CREATE TABLE air_quality
(
ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
date_time TIMESTAMP NULL,
location VARCHAR(255),
no2 DECIMAL(4,1),
o3 DECIMAL(4,1),
so2 DECIMAL(4,1),
co DECIMAL(4,1),
pm10 DECIMAL(4,1),
pm25 DECIMAL(4,1),
aqi INT,
health_range VARCHAR(255),
exec_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
loc_code VARCHAR(255)
)
